---
title: "Using STvEA to analyze CODEX data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(STvEA)
```

## Read in CODEX data
```{r}
data("codex_balbc1")
protein_expr <- cbind(codex_balbc1[, 1:29], MHCII=codex_balbc1$MHCII)
blanks <- codex_balbc1[,grepl("blank", colnames(codex_balbc1))]
size <- codex_balbc1$size.size
x <- codex_balbc1$X.X
x <- floor((codex_balbc1$tile_nr.tile_nr-1)/9) * max(codex_balbc1$X.X) + x
y <- codex_balbc1$Y.Y
y <- ((codex_balbc1$tile_nr.tile_nr - 1) %% 9) * max(codex_balbc1$Y.Y) + y
z <- codex_balbc1$Z.Z
spatial <- cbind(x,y,z)
row.names(spatial) <- row.names(protein_expr)
```

```{r}
codex_subset <- x < 3000 & y < 3000
protein_expr <- protein_expr[codex_subset,]
blanks <- blanks[codex_subset,]
size <- size[codex_subset]
spatial <- spatial[codex_subset,]
```

## Create object to hold data
```{r}
stvea_object <- SetDataCODEX(codex_protein = protein_expr, codex_blanks = blanks, codex_size = size, codex_spatial = as.data.frame(spatial))
```

## Filter and clean protein protein_expr
```{r}
stvea_object <- FilterCODEX(stvea_object, size_lim = c(1000,25000), blank_lower = c(-1200, -1200, -1200, -1200), blank_upper = c(6000,2500,5000,2500))

stvea_object <- CleanCODEX(stvea_object)
```

## Louvain clustering on KNN from UMAP
```{r}
# Takes ~5 minutes with ~10000 cells
ptm <- proc.time()
stvea_object <- GetVisUMAP(stvea_object, metric = 'pearson', n_neighbors=30, min_dist=0.1, negative_sample_rate = 50)

stvea_object <- ClusterCODEX(stvea_object, k=30)
proc.time() - ptm
```

## Visualize clustering and protein expression on UMAP 
```{r}
PlotClusterCODEXemb(stvea_object)
```

```{r}
PlotExprCODEXemb(stvea_object, "CD4")
```

## Assess colocalization of clusters
```{r}
cluster_adj <- AdjScoreClustersCODEX(stvea_object, k=3)
```

```{r}
protein_pairs <- t(combn(colnames(protein_expr),2))
for (protein in colnames(protein_expr)) {
  protein_pairs <- rbind(protein_pairs, c(protein,protein))
}
protein_adj <- AdjScoreProteins(stvea_object, protein_pairs, k=3, num_cores=8)
```
